import type { FunnelGeneration } from "@/server/ai/generation-schema";

/**
 * Contenido de las 5 plantillas iniciales del MVP (sección 16 del spec).
 * Cada config usa el mismo shape que la salida del generador de IA
 * (referencias por índice/key), así que se materializan con el mismo
 * `materializeFunnelFromSpec` que usa "Crear con IA".
 */
export interface TemplateDefinition {
  name: string;
  description: string;
  category: string;
  config: FunnelGeneration;
}

const THEME = { primaryColor: "#1d3f52", backgroundColor: "#fcfbf9" };

export const TEMPLATE_LIBRARY: TemplateDefinition[] = [
  {
    name: "Captación de leads",
    description: "Un funnel de propósito general para calificar y captar cualquier tipo de lead.",
    category: "Lead Generation",
    config: {
      name: "Captación de leads",
      goal: "Captar leads cualificados",
      industry: "General",
      audience: "Personas interesadas en tus productos o servicios",
      intro: {
        headline: "Cuéntanos qué buscas y te ayudamos",
        subheadline: "Responde 4 preguntas rápidas para que podamos orientarte mejor.",
        buttonText: "Empezar",
      },
      questions: [
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué te trae por aquí hoy?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Busco información" },
            { label: "Quiero comparar opciones" },
            { label: "Ya sé lo que quiero" },
            { label: "Solo estoy explorando" },
          ],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Cuándo te gustaría dar el siguiente paso?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Esta semana" },
            { label: "Este mes" },
            { label: "En los próximos 3 meses" },
            { label: "Todavía no lo sé" },
          ],
        },
        {
          type: "YES_NO",
          title: "¿Has trabajado antes con una empresa como la nuestra?",
          description: null,
          required: true,
          scaleMax: null,
          options: [{ label: "Sí" }, { label: "No" }],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué es lo más importante para ti al elegir?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Precio" },
            { label: "Calidad" },
            { label: "Rapidez" },
            { label: "Atención personalizada" },
          ],
        },
      ],
      profiles: [
        {
          key: "lead-prioritario",
          title: "Lead prioritario",
          description: "Muestra intención clara de avanzar pronto. Vale la pena contactarlo cuanto antes.",
          recommendation: "Llámalo o escríbele hoy mismo; es el momento de mayor interés.",
        },
        {
          key: "lead-exploracion",
          title: "Lead en exploración",
          description: "Todavía está comparando opciones y no tiene prisa por decidir.",
          recommendation: "Nútrelo con contenido de valor antes de insistir en la venta.",
        },
      ],
      rules: [
        { questionIndex: 0, optionIndex: 2, profileKey: "lead-prioritario", points: 3 },
        { questionIndex: 0, optionIndex: 0, profileKey: "lead-exploracion", points: 2 },
        { questionIndex: 0, optionIndex: 3, profileKey: "lead-exploracion", points: 3 },
        { questionIndex: 1, optionIndex: 0, profileKey: "lead-prioritario", points: 3 },
        { questionIndex: 1, optionIndex: 1, profileKey: "lead-prioritario", points: 2 },
        { questionIndex: 1, optionIndex: 2, profileKey: "lead-exploracion", points: 2 },
        { questionIndex: 1, optionIndex: 3, profileKey: "lead-exploracion", points: 3 },
        { questionIndex: 2, optionIndex: 0, profileKey: "lead-prioritario", points: 1 },
        { questionIndex: 2, optionIndex: 1, profileKey: "lead-exploracion", points: 1 },
        { questionIndex: 3, optionIndex: 2, profileKey: "lead-prioritario", points: 1 },
        { questionIndex: 3, optionIndex: 3, profileKey: "lead-prioritario", points: 1 },
      ],
      leadCapture: {
        title: "¿Dónde te contactamos?",
        position: "before_result",
        askPhone: true,
        consentText: "Acepto recibir información comercial sobre productos y servicios.",
      },
      cta: {
        type: "whatsapp",
        label: "Hablar por WhatsApp",
        value: "",
        whatsappMessage:
          "Hola, completé el test {{funnel_name}} y mi resultado fue {{result_name}}. Quisiera recibir más información.",
        resultNote: "",
      },
      theme: THEME,
    },
  },
  {
    name: "Encuentra tu producto ideal",
    description: "Ayuda al visitante a elegir el producto de tu catálogo que mejor encaja con él.",
    category: "Product Finder",
    config: {
      name: "Encuentra tu producto ideal",
      goal: "Recomendar un producto",
      industry: "Retail / E-commerce",
      audience: "Compradores indecisos entre varias opciones de tu catálogo",
      intro: {
        headline: "Encuentra el producto ideal para ti",
        subheadline: "Responde unas preguntas y te recomendamos la mejor opción de nuestro catálogo.",
        buttonText: "Empezar",
      },
      questions: [
        {
          type: "SINGLE_CHOICE",
          title: "¿Para qué lo vas a usar principalmente?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Uso diario" },
            { label: "Ocasiones especiales" },
            { label: "Regalo para alguien" },
            { label: "Uso profesional" },
          ],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Cuál es tu prioridad al comprar?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "El mejor precio" },
            { label: "La mejor calidad" },
            { label: "Que dure mucho" },
            { label: "Que sea fácil de usar" },
          ],
        },
        {
          type: "SCALE",
          title: "Del 1 al 5, ¿qué tan urgente es tu compra?",
          description: null,
          required: true,
          scaleMax: 5,
          options: [],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Cuál es tu presupuesto aproximado?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Económico" },
            { label: "Medio" },
            { label: "Premium" },
            { label: "Sin límite definido" },
          ],
        },
      ],
      profiles: [
        {
          key: "producto-basico",
          title: "Línea Esencial",
          description: "Buscas algo funcional y accesible, sin complicaciones.",
          recommendation: "Nuestra línea Esencial te da lo que necesitas al mejor precio.",
        },
        {
          key: "producto-medio",
          title: "Línea Equilibrada",
          description: "Quieres un buen balance entre precio, calidad y durabilidad.",
          recommendation: "Nuestra línea Equilibrada es la más elegida por su relación calidad-precio.",
        },
        {
          key: "producto-premium",
          title: "Línea Premium",
          description: "Priorizas la mejor calidad y estás dispuesto/a a invertir en ello.",
          recommendation: "Nuestra línea Premium está pensada para quien no quiere hacer concesiones.",
        },
      ],
      rules: [
        { questionIndex: 1, optionIndex: 0, profileKey: "producto-basico", points: 3 },
        { questionIndex: 3, optionIndex: 0, profileKey: "producto-basico", points: 3 },
        { questionIndex: 1, optionIndex: 1, profileKey: "producto-premium", points: 2 },
        { questionIndex: 3, optionIndex: 2, profileKey: "producto-premium", points: 3 },
        { questionIndex: 3, optionIndex: 3, profileKey: "producto-premium", points: 3 },
        { questionIndex: 1, optionIndex: 2, profileKey: "producto-medio", points: 2 },
        { questionIndex: 3, optionIndex: 1, profileKey: "producto-medio", points: 3 },
        { questionIndex: 1, optionIndex: 3, profileKey: "producto-medio", points: 1 },
        { questionIndex: 0, optionIndex: 2, profileKey: "producto-medio", points: 1 },
        { questionIndex: 0, optionIndex: 3, profileKey: "producto-premium", points: 1 },
      ],
      leadCapture: {
        title: "Te enviamos la recomendación a tu correo",
        position: "before_result",
        askPhone: false,
        consentText: "Acepto recibir recomendaciones de producto por email.",
      },
      cta: {
        type: "url",
        label: "Ver producto recomendado",
        value: "",
        whatsappMessage: "",
        resultNote: "",
      },
      theme: THEME,
    },
  },
  {
    name: "Descubre tu servicio ideal",
    description: "Orienta al visitante hacia el servicio de tu negocio que mejor resuelve su necesidad.",
    category: "Service Matcher",
    config: {
      name: "Descubre tu servicio ideal",
      goal: "Recomendar un servicio",
      industry: "Servicios profesionales",
      audience: "Personas que dudan entre varios servicios de tu negocio",
      intro: {
        headline: "Descubre qué servicio es para ti",
        subheadline: "En menos de 2 minutos te decimos cuál de nuestros servicios encaja mejor contigo.",
        buttonText: "Empezar",
      },
      questions: [
        {
          type: "SINGLE_CHOICE",
          title: "¿Cuál es tu principal objetivo ahora mismo?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Resolver un problema puntual" },
            { label: "Mejorar algo de forma continua" },
            { label: "Prevenir problemas futuros" },
            { label: "Aprender o entender más" },
          ],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Cuánta experiencia previa tienes en esto?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Ninguna" },
            { label: "Algo de experiencia" },
            { label: "Bastante experiencia" },
            { label: "Soy experto o experta" },
          ],
        },
        {
          type: "YES_NO",
          title: "¿Necesitas resultados con urgencia?",
          description: null,
          required: true,
          scaleMax: null,
          options: [{ label: "Sí" }, { label: "No" }],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Prefieres un servicio puntual o continuo?",
          description: null,
          required: true,
          scaleMax: null,
          options: [{ label: "Puntual (una vez)" }, { label: "Continuo (recurrente)" }],
        },
      ],
      profiles: [
        {
          key: "servicio-diagnostico",
          title: "Servicio de Diagnóstico",
          description: "Necesitas resolver algo concreto, de forma rápida y puntual.",
          recommendation: "Te recomendamos empezar con una sesión de diagnóstico enfocada en tu problema.",
        },
        {
          key: "servicio-acompanamiento",
          title: "Servicio de Acompañamiento",
          description: "Buscas mejorar de forma sostenida, con seguimiento en el tiempo.",
          recommendation: "Nuestro servicio de acompañamiento continuo se ajusta a lo que necesitas.",
        },
        {
          key: "servicio-integral",
          title: "Servicio Integral",
          description: "Quieres entender el tema a fondo y partes con poca experiencia previa.",
          recommendation: "Nuestro servicio integral combina formación y acompañamiento desde cero.",
        },
      ],
      rules: [
        { questionIndex: 0, optionIndex: 0, profileKey: "servicio-diagnostico", points: 3 },
        { questionIndex: 3, optionIndex: 0, profileKey: "servicio-diagnostico", points: 3 },
        { questionIndex: 0, optionIndex: 1, profileKey: "servicio-acompanamiento", points: 3 },
        { questionIndex: 3, optionIndex: 1, profileKey: "servicio-acompanamiento", points: 2 },
        { questionIndex: 0, optionIndex: 2, profileKey: "servicio-acompanamiento", points: 2 },
        { questionIndex: 0, optionIndex: 3, profileKey: "servicio-integral", points: 2 },
        { questionIndex: 1, optionIndex: 0, profileKey: "servicio-integral", points: 2 },
        { questionIndex: 1, optionIndex: 3, profileKey: "servicio-diagnostico", points: 1 },
        { questionIndex: 2, optionIndex: 0, profileKey: "servicio-diagnostico", points: 2 },
        { questionIndex: 2, optionIndex: 1, profileKey: "servicio-acompanamiento", points: 1 },
      ],
      leadCapture: {
        title: "Cuéntanos cómo contactarte",
        position: "before_result",
        askPhone: true,
        consentText: "Acepto que me contacten para coordinar el servicio.",
      },
      cta: {
        type: "booking",
        label: "Reservar una llamada",
        value: "",
        whatsappMessage: "",
        resultNote: "",
      },
      theme: THEME,
    },
  },
  {
    name: "Test de autoevaluación",
    description: "Un quiz con score que ubica al visitante en un nivel y le da una recomendación acorde.",
    category: "Quiz / Score",
    config: {
      name: "Test de autoevaluación",
      goal: "Realizar un diagnóstico orientativo",
      industry: "Educación / Bienestar",
      audience: "Personas que quieren conocer su nivel actual",
      intro: {
        headline: "Descubre tu nivel en menos de 2 minutos",
        subheadline: "Responde con sinceridad; al final verás tu resultado y una recomendación para avanzar.",
        buttonText: "Empezar test",
      },
      questions: [
        {
          type: "SCALE",
          title: "Del 1 al 5, ¿qué tan seguro te sientes en este tema?",
          description: null,
          required: true,
          scaleMax: 5,
          options: [],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Con qué frecuencia practicas o aplicas esto?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Nunca" },
            { label: "Rara vez" },
            { label: "A veces" },
            { label: "Frecuentemente" },
          ],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué tan preparado te sientes para el siguiente nivel?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Nada preparado" },
            { label: "Poco preparado" },
            { label: "Bastante preparado" },
            { label: "Totalmente preparado" },
          ],
        },
        {
          type: "YES_NO",
          title: "¿Has recibido formación o guía profesional antes?",
          description: null,
          required: true,
          scaleMax: null,
          options: [{ label: "Sí" }, { label: "No" }],
        },
      ],
      profiles: [
        {
          key: "nivel-inicial",
          title: "Nivel Inicial",
          description: "Estás dando tus primeros pasos; hay una gran oportunidad de mejora.",
          recommendation: "Empieza por lo básico con acompañamiento cercano.",
        },
        {
          key: "nivel-intermedio",
          title: "Nivel Intermedio",
          description: "Ya tienes bases sólidas y practicas con cierta regularidad.",
          recommendation: "Un programa de profundización te ayudará a dar el salto.",
        },
        {
          key: "nivel-avanzado",
          title: "Nivel Avanzado",
          description: "Tienes buen dominio y aplicas esto con frecuencia.",
          recommendation: "Te beneficiaría un programa avanzado enfocado en optimización.",
        },
      ],
      rules: [
        { questionIndex: 1, optionIndex: 0, profileKey: "nivel-inicial", points: 3 },
        { questionIndex: 1, optionIndex: 1, profileKey: "nivel-inicial", points: 2 },
        { questionIndex: 1, optionIndex: 2, profileKey: "nivel-intermedio", points: 3 },
        { questionIndex: 1, optionIndex: 3, profileKey: "nivel-avanzado", points: 3 },
        { questionIndex: 2, optionIndex: 0, profileKey: "nivel-inicial", points: 2 },
        { questionIndex: 2, optionIndex: 1, profileKey: "nivel-intermedio", points: 1 },
        { questionIndex: 2, optionIndex: 2, profileKey: "nivel-intermedio", points: 2 },
        { questionIndex: 2, optionIndex: 3, profileKey: "nivel-avanzado", points: 2 },
        { questionIndex: 3, optionIndex: 0, profileKey: "nivel-avanzado", points: 1 },
        { questionIndex: 3, optionIndex: 1, profileKey: "nivel-inicial", points: 1 },
      ],
      leadCapture: {
        title: "Recibe tu resultado detallado",
        position: "before_result",
        askPhone: false,
        consentText: "Acepto recibir mi resultado y contenido relacionado por email.",
      },
      cta: {
        type: "url",
        label: "Quiero mejorar mi nivel",
        value: "",
        whatsappMessage: "",
        resultNote: "",
      },
      theme: THEME,
    },
  },
  {
    name: "Reserva tu cita",
    description: "Orientado a negocios con agenda: prioriza y canaliza visitantes hacia reservar una cita.",
    category: "Appointment Funnel",
    config: {
      name: "Reserva tu cita",
      goal: "Conseguir reservas",
      industry: "Salud / Estética / Servicios con cita",
      audience: "Personas interesadas en agendar una cita o consulta",
      intro: {
        headline: "Reserva tu cita en menos de 2 minutos",
        subheadline: "Cuéntanos qué necesitas y te ayudamos a encontrar el horario ideal.",
        buttonText: "Empezar",
      },
      questions: [
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué tipo de cita buscas?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Primera consulta" },
            { label: "Seguimiento" },
            { label: "Consulta urgente" },
            { label: "Aún no lo sé" },
          ],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué horario prefieres?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Mañana" },
            { label: "Tarde" },
            { label: "Fin de semana" },
            { label: "Cualquiera" },
          ],
        },
        {
          type: "YES_NO",
          title: "¿Es tu primera vez con nosotros?",
          description: null,
          required: true,
          scaleMax: null,
          options: [{ label: "Sí" }, { label: "No, ya soy cliente" }],
        },
        {
          type: "SINGLE_CHOICE",
          title: "¿Qué tan pronto quieres tu cita?",
          description: null,
          required: true,
          scaleMax: null,
          options: [
            { label: "Lo antes posible" },
            { label: "Esta semana" },
            { label: "Este mes" },
            { label: "Sin prisa" },
          ],
        },
      ],
      profiles: [
        {
          key: "cita-prioritaria",
          title: "Cita Prioritaria",
          description: "Necesitas ser atendido/a con relativa urgencia.",
          recommendation: "Te contactaremos hoy mismo para coordinar tu cita cuanto antes.",
        },
        {
          key: "cita-estandar",
          title: "Cita Estándar",
          description: "Puedes esperar el horario habitual de agenda.",
          recommendation: "Te ofreceremos las próximas fechas disponibles según tu preferencia.",
        },
      ],
      rules: [
        { questionIndex: 0, optionIndex: 2, profileKey: "cita-prioritaria", points: 3 },
        { questionIndex: 3, optionIndex: 0, profileKey: "cita-prioritaria", points: 3 },
        { questionIndex: 3, optionIndex: 1, profileKey: "cita-prioritaria", points: 2 },
        { questionIndex: 3, optionIndex: 2, profileKey: "cita-estandar", points: 2 },
        { questionIndex: 3, optionIndex: 3, profileKey: "cita-estandar", points: 3 },
        { questionIndex: 0, optionIndex: 0, profileKey: "cita-estandar", points: 1 },
        { questionIndex: 0, optionIndex: 1, profileKey: "cita-estandar", points: 1 },
        { questionIndex: 2, optionIndex: 0, profileKey: "cita-estandar", points: 1 },
        { questionIndex: 2, optionIndex: 1, profileKey: "cita-prioritaria", points: 1 },
      ],
      leadCapture: {
        title: "Confirma tus datos para tu cita",
        position: "before_result",
        askPhone: true,
        consentText: "Acepto ser contactado/a para confirmar mi cita.",
      },
      cta: {
        type: "booking",
        label: "Confirmar mi cita",
        value: "",
        whatsappMessage: "",
        resultNote: "",
      },
      theme: THEME,
    },
  },
];
